services:
  frontend:
    container_name: nuxt-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://mvp-0exw.onrender.com
      
    env_file:
      - ./frontend/.env
    command: ["pnpm", "dev", "--host", "0.0.0.0"]

  backend:
    container_name: flask-backend
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URI=mongodb+srv://kaingbunly9999:hQeACKZzuVMOZkM1@dev.xszgj1j.mongodb.net/school_db?retryWrites=true&w=majority&appName=dev
    command: ["python", "run.py"]

volumes:
  node_modules: