services:
  frontend:
    container_name: nuxt-frontend
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev", "--host", "0.0.0.0"]

  backend:
    container_name: flask-backend
    build: ./backend
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_RUN_HOST=0.0.0.0
    command: ["python", "run.py"]
