services:
  - type: web
    name: backend-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    envVars:
      - key: DATABASE_URI
        value: mongodb+srv://kaingbunly9999:hQeACKZzuVMOZkM1@dev.xszgj1j.mongodb.net/?retryWrites=true&w=majority&appName=dev
      - key: SECRET_KEY
        value: f3a9d8e6c52b47a1bfa3d97e0cfc3f5d1b2a7c6e8f493a0d4e7b8c2f9a1d6e3b
      - key: TELEGRAM_BOT_TOKEN
        value: 7896472500:AAGvkX4LH0U7ptvU_wdT-wMtz8LUU5rDuPU
      - key: GOOGLE_CLIENT_ID
        value: 881284718033-8440nvsmk39817kru0r98sfkj10kpl60.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
